# Tensor Network Renormalization Group for the 2D Ising model

In [19]:
import functools
import matplotlib.pyplot as plt
import numpy
import itertools

Define the basic functions for the Ising model

Define Kronecker Delta

In [2]:
def kronecker(i: int, j: int) -> int:
    return int(i == j)

In [3]:
kronecker(1,1), kronecker(0,1)

(1, 0)

Define the weight functions of Ising model

$Z_2$ has two representations, $k=0$ and $k=1$. The weight on an edge is $\cosh(\beta)$ for $k=0$, $\sinh(\beta)$ for $k=1$.

In [4]:
def weight(beta: float, k: int) -> float:
    return (1 - k) * numpy.cosh(beta) + k * numpy.sinh(beta)

In [6]:
weight(0, 0), weight(0, 1), weight(1.5, 0)

(1.0, 0.0, 2.352409615243247)

Define the initial tensor

The tensor is 4-valent, each edge carrying a representation of $Z_2$, and a square root of an edge weight (for $\beta$ and $k$). On the vertex, we have a Kronecker Delta of the sum of the 4 representations meeting at the vertex modulo 2; if this sum is 1, it vanishes.

In [7]:
def tensor(beta: float, m: int = 2):
    r = numpy.arange(0, m) # give us the [0, 1] range which we'll use for each axis
    iv, jv, kv, lv = numpy.meshgrid(*(4*[r])) # compute vectorized "index" tensors - numerical
    # trick for making this recipe a few orders of magnitude faster
    raw = numpy.sqrt(weight(beta, iv) * weight(beta, jv) * weight(beta, kv) * weight(beta, lv))
    delta_mask = 1 - ((iv + jv + kv + lv) % m)
    return delta_mask * raw

In [32]:
t = tensor(beta=1.0)
t

array([[[[2.38109785, 0.        ],
         [0.        , 1.8134302 ]],

        [[0.        , 1.8134302 ],
         [1.8134302 , 0.        ]]],


       [[[0.        , 1.8134302 ],
         [1.8134302 , 0.        ]],

        [[1.8134302 , 0.        ],
         [0.        , 1.38109785]]]])

In [33]:
len(t[:,0,0,0])

2

Splitting tensors for the singular value decomposition

This will be similar to the introductory Julia File. We pair the indices of the tensor in the way we want to split it, and define a matrix. On this matrix we will apply a singular value decomposition, truncate here at 2 singular values, and define new 3-valent tensors from it.

Translating back just means splitting the combined index again into two separate ones.

The function should return two 3-valent tensors and a list of singular values.

Normalize the singular values with respect to the largest one (so the largest singular value is always one).

In [34]:
m = t.reshape((4, 4))

In [35]:
i, j, k, l = (0, 1, 1, 0)

In [36]:
for i, j, k, l in itertools.product(*4*[range(2)]): 
    t_ijkl = t[i, j, k, l]
    a = i + 2*j
    b = k + 2*l
    m_ab = m[a, b]
    print(numpy.isclose(t_ijkl, m_ab), t_ijkl, m_ab)

True 2.3810978455418157 2.3810978455418157
True 0.0 0.0
True 0.0 0.0
True 1.813430203923509 1.813430203923509
True 0.0 0.0
True 1.813430203923509 1.8134302039235093
True 1.8134302039235093 1.813430203923509
True 0.0 0.0
True 0.0 0.0
True 1.813430203923509 1.8134302039235093
True 1.8134302039235093 1.813430203923509
True 0.0 0.0
True 1.813430203923509 1.813430203923509
True 0.0 0.0
True 0.0 0.0
True 1.3810978455418155 1.3810978455418155


In [37]:
u, l, v = numpy.linalg.svd(m)

In [38]:
u

array([[-0.79555082,  0.        ,  0.60588686,  0.        ],
       [ 0.        , -0.70710678,  0.        , -0.70710678],
       [ 0.        , -0.70710678,  0.        ,  0.70710678],
       [-0.60588686,  0.        , -0.79555082,  0.        ]])

In [39]:
l

array([3.76219569e+00, 3.62686041e+00, 4.50858600e-16, 5.88433855e-17])

In [40]:
v

array([[-0.79555082,  0.        ,  0.        , -0.60588686],
       [-0.        , -0.70710678, -0.70710678,  0.        ],
       [ 0.60588686,  0.        ,  0.        , -0.79555082],
       [-0.        , -0.70710678,  0.70710678,  0.        ]])

We need to the same again, but this time for the other splitting.

To get the new effective tensor, we now have to contract the fine degrees of freedom.

To compute the flow of renormalized tensors, we have to iterate these procedures a few times. We write this into a main function.

We have to specify the number of iterations of the algorithm, then define the initial tensor. We can pass $\beta$ as a parameter of the main function.

Then we do a for loop, in which we do the first splitting, second splitting and then contract the new three valent tensor. Then we repeat.

For each iteration we should store the singular values computed in the singular value decomposition. We will afterwards plot them to distinguish the phases of the Ising model and finding the phase transition.